---
- name: install remote server
  hosts: webservers
  become: yes 
  
  tasks:
  - name: Install list of packages
    action: yum pkg={{item}} state=installed
    with_items:
      - apache2
      - sqlite3
      - git
