---
- name: install apache2, sqlite3, git pn remote server
  hosts: webservers
  sudo: yes
  tasks:
  - name: Install list of packages
    action: yum pkg={{item}} state=installed
    with_items:
      - apache2
      - sqlite3
      - git
